<?php
/*=========================================================================
MIDDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.
See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/dashboard/index.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/common/common.browser.js');
$this->headScript()->appendFile($this->apiWebroot.'/public/js/common/common.ajaxapi.js');
?>
<div class="viewMain">
    <div id="tabs-data">

                <table id="curateDashboardTable" class="midasTree">
                    <thead>
                    <th class="thDataset"><?php echo $this->t('Dataset'); ?></th>
                    <th class="thCurationState"><?php echo $this->t('Curation State'); ?></th>
                    <th class="thSizeBytes"><?php echo $this->t('Size Bytes'); ?></th>
                    <th class="thDownloads"><?php echo $this->t('Downloads'); ?></th>
                    <th class="thAction"><?php echo $this->t('Action'); ?></th>
                    </thead>
                    <tbody>
                    <?php
                    foreach ($this->curatedFolders as $curated) {
                        $size = $curated['size'];
                        $download = $curated['download'];
                        $folder_id = $curated['folder_id'];
                        $curatedfolder_id = $curated['curatedfolder_id'];
                        $name = $curated['name'];
                        $curation_state = $curated['curation_state'];
                        echo "<tr id='curatedFolder{$this->escape($folder_id)}'>";
                        echo "  <td><a href=\"/folder/{$folder_id}\">{$name}</a></td>";
                        echo "  <td class='curationState'>{$curation_state}</td>";
                        echo "  <td>{$size}</td>";
                        echo "  <td>{$download}</td>";
                        echo "  <td class='curationAction'>";
                        if ($this->isAdmin) {
                           if($curation_state == CURATE_STATE_CONSTRUCTION) {
                               echo "<img src=\"/core/public/images/icons/time.png\" style=\"padding-right: 5px;\">wait for request";
                           } else if ($curation_state == CURATE_STATE_REQUESTED) {
                               echo "<a onclick=\"midas.curate.adminApprove($folder_id);\"><img src=\"/core/public/images/icons/ok.png\" style=\"padding-right: 5px;\">approve request</a>";
                           } else if ($curation_state == CURATE_STATE_APPROVED) {
                               //
                           }
                        } else {
                           if($curation_state == CURATE_STATE_CONSTRUCTION) {
                               echo "<a onclick=\"midas.curate.uploaderRequestApproval($folder_id);\"><img src=\"/core/public/images/icons/lock.png\" style=\"padding-right: 5px;\">request approval</a>";
                           } else if ($curation_state == CURATE_STATE_REQUESTED) {
                               echo "<img src=\"/core/public/images/icons/time.png\" style=\"padding-right: 5px;\">wait for approval";
                           } else if ($curation_state == CURATE_STATE_APPROVED) {
                               //
                           }
                        }
                        echo "</tr>";
                    }
                    ?>

                    </tbody>
                </table>
    </div>
</div>
<div class="viewSideBar">
    <div class='sideElementFirst genericAction'>
        <?php if ($this->isAdmin) {
            echo "<h1>Curator Actions</h1>";
            echo "<ul>";
            echo "<li><a onclick='midas.curate.createNewCuratedFolder();'><img alt='' src='{$this->coreWebroot}/public/images/icons/folder_add.png'/> {$this->t(
                        'Create a Curated Folder'
                    )}</a></li>";
                  }
            echo "</ul>";
        ?>
    </div>
    <div class="sideElement viewSelected">
       <h1><?php echo $this->t('Checked') ?><span></span></h1>
       <span></span>
    </div>
</div>
